part of 'translations.dart';

final enUs = {
  StringRes.appName: "Physical Note",
  StringRes.bottomTabData: "데이터",
  StringRes.bottomTabHome: "홈",
  StringRes.bottomTabFeedback: "피드백",
  StringRes.email: "이메일",
  StringRes.emailHint: "이메일 주소를 입력하세요.",
  StringRes.emailError: "바른 이메일 양식을 입력해주세요.",
  StringRes.password: "비밀번호",
  StringRes.passwordHint: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordError: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordConfirm: "비밀번호 확인",
  StringRes.passwordNotMatched: "비밀번호가 일치하지 않습니다.",
  StringRes.simpleSignUp: "간편 회원가입",
  StringRes.findId: "아이디 찾기",
  StringRes.findPw: "비밀번호 찾기",
  StringRes.login: "로그인",
  StringRes.startWithSns: "SNS 계정으로 시작하기",
  StringRes.acceptTerms: "서비스 이용을 위해\n약관에 동의해주세요.",
  StringRes.allAgree: "전체 동의",
  StringRes.requiredTermService: "[필수] 서비스 이용약관",
  StringRes.requiredTermPrivacy: "[필수] 개인정보 수집 및 이용 동의",
  StringRes.next: "다음",
  StringRes.prev: "이전",
  StringRes.signUp: "회원가입",
  StringRes.phoneNumber: "휴대폰 번호",
  StringRes.phoneHint: "( - )없이 11자리를 입력하세요.",
  StringRes.phoneNumberError: "올바른 전화번호를 입력해주세요.",
  StringRes.name: "이름",
  StringRes.nameError: "2자리 이상 이름을 입력해주세요.",
  StringRes.nameHint: "이름을 입력하세요.",
  StringRes.findIdResult: "@name님의 아이디느\n@email 입니다.",
  StringRes.changePassword: "비밀번호 재설정",
  StringRes.category: "종목",
  StringRes.sports: "스포츠",
  StringRes.clickToSelect: "눌러 선택하세요.",
  StringRes.amateur: "아마추어",
  StringRes.elite: "엘리트",
  StringRes.selectCategory: "종목 선택",
  StringRes.selectSports: "스포츠 선택",
  StringRes.search: "검색",
  StringRes.select: "선택",
  StringRes.myInformation: "내정보",
  StringRes.teamName: "팀명",
  StringRes.selectTeam: "소속된 팀명을 선택해주세요.",
  StringRes.height: "키",
  StringRes.weight: "몸무게",
  StringRes.cm: "cm",
  StringRes.kg: "kg",
  StringRes.birth: "생년월일",
  StringRes.gender: "성별",
  StringRes.eightDigits: "8자리",
  StringRes.positionMultipleSelectionPossible: "포지션(다중선택가능)",
  StringRes.mainFoot: "주 발",
  StringRes.leftFoot: "왼쪽 발",
  StringRes.rightFoot: "오른쪽 발",
  StringRes.registration: "등록",
  StringRes.confirm: "확인",
  StringRes.sir: "님",
  StringRes.myState: "나의 상태",
  StringRes.noData: "데이터\n없음",
  StringRes.hooperIndex: "후퍼인덱스",
  StringRes.urinalysis: "소변검사",
  StringRes.urinalysisTable: "소변검사표",
  StringRes.injuryRisk: "부상위험도",
  StringRes.workoutIntensity: "운동강도",
  StringRes.noRecordAndRecordYourStatusToday: "기록가 없습니다. 오늘 상태를 기록하세요!",
  StringRes.emptyWeightParams: "공복 몸무게 : @weight kg",
  StringRes.emptyWeightWarning: "✔ 수분 섭취 상태와 함께 식단 조절에 신경쓰세요.",
  StringRes.emptyWeightGood: "✔ 식단조절에 신경쓰세요.",
  StringRes.workoutIntensityStatistics: "운동 강도 통계",
  StringRes.physical: "피지컬",
  StringRes.pleaseSelectCategory: "종목을 선택해주세요.",
  StringRes.monthly: "월간",
  StringRes.weekly: "주간",
  StringRes.sleep: "수면의 질",
  StringRes.sleepKorEng: "수면의 질(sleep)",
  StringRes.sleepEng: "sleep",
  StringRes.stress: "스트레스",
  StringRes.stressKorEng: "스트레스(stress)",
  StringRes.stressEng: "stress",
  StringRes.fatigue: "피로",
  StringRes.fatigueKorEng: "피로(fatigue)",
  StringRes.fatigueEng: "fatigue",
  StringRes.musclePain: "근육통",
  StringRes.musclePainKorEng: "근육통(muscleSoreness)",
  StringRes.musclePainEng: "muscleSoreness",
  StringRes.urineVeryGood: "매우 양호",
  StringRes.urineGood: "양호",
  StringRes.urineAppropriate: "적정",
  StringRes.urineDemand: "수분 섭취 요망",
  StringRes.urineRecommended: "수분 섭취 권장",
  StringRes.urineNeed: "수분 섭취  필요",
  StringRes.urineEmergency: "수분 부족 위급",
  StringRes.urineNone: "정보 없음",
  StringRes.workoutTime: "운동시간",
  StringRes.todayTime: "오늘의 시간",
  StringRes.trainingBalance: "트레이닝 밸런스",
  StringRes.trainingBalanceFormula: "(운동강도 X 운동시간) 평균 값",
  StringRes.thisWeek: "이번주",
  StringRes.lastWeek: "저번주",
  StringRes.lastFourWeek: "지난4주",
  StringRes.lastEightWeek: "지난8주",
  StringRes.unitPercent: "(단위: %)",
  StringRes.informationRegistrationGuide : "추가정보를 등록해야만\n앱을 사용할 수 있습니다.",
  StringRes.doInformationRegistration: "정보등록 하기",
  StringRes.wellness: "웰리니스",
  StringRes.wellnessKorEng: "웰리니스 (Wellness)",
  StringRes.wellnessDescription: "팀 내 피지컬 코치 및 운동코치 또는 선수 개인이 웰리니스 관련 데이터를 수집하고 분석함으로써 운동 컨디션 및 삶의 질을 관리하고, 부상을 보다 효과적으로 예방하는데 도움이 됩니다. 뿐만아니라, 경기력 향상 및 유지하는데 또한 도움이 됩니다.",
  StringRes.injuryCheck: "부상체크",
  StringRes.close: "닫기",
  StringRes.open: "열기",
  StringRes.veryVeryGood: "매우, 매우 좋은",
  StringRes.veryVeryBad: "매우, 매우 나쁜",
  StringRes.satisfactory: "양호한",
  StringRes.insufficient: "부족한",
  StringRes.urineTestWeightKg: "소변 검사 직후 공복 상태 몸무게 (kg)",
  StringRes.myAnswer: "내 답변",
  StringRes.bmiPercent: "체지방률(%)",
  StringRes.compellingRequest: "대략적으로 작성해주세요.",
  StringRes.doSave: "저장하기",
  StringRes.doUpdate: "수정하기",
  StringRes.hourParams: "@hour시간",
  StringRes.minParams: "@min분",
};
