part of 'translations.dart';

final enUs = {
  ..._enMuscleName,
  StringRes.appName: "Physical Note",
  StringRes.serverError: 'Server Error',
  StringRes.notification: "알림",
  StringRes.message: "메시지",
  StringRes.messageChannelDescription: "메시지 알림",
  StringRes.bottomTabHistory: "History",
  StringRes.bottomTabHome: "Home",
  StringRes.bottomTabFeedback: "Feedback",
  StringRes.email: "Email",
  StringRes.emailHint: "Enter your email address",
  StringRes.emailError: "Please enter a valid email address.",
  StringRes.emailDuplicated: "Duplicated Email.",
  StringRes.password: "Password",
  StringRes.passwordHint: "Please enter your PIN number",
  StringRes.passwordError:
      "8 characters or more including English +\nspecial characters + numbers",
  StringRes.passwordConfirm: "Confirm password",
  StringRes.passwordNotMatched: "Passwords do not match",
  StringRes.simpleSignUp: "Sign-Up",
  StringRes.findId: "Find ID",
  StringRes.findPw: "Find Password",
  StringRes.login: "Login",
  StringRes.logout: "Logout",
  StringRes.startWithSns: "Start with SNS Account",
  StringRes.acceptTerms: "Terms of\nService Agreement",
  StringRes.allAgree: "Agree to all",
  StringRes.requiredTermService: "[Required] Terms of Service Agreement",
  StringRes.requiredTermPrivacy:
      "[Required] Consent to the Collection and Use of Personal Information",
  StringRes.next: "Next",
  StringRes.prev: "Previous",
  StringRes.signUp: "Sign-Up",
  StringRes.phoneNumber: "Phone Number",
  StringRes.phoneHint: "Enter phone number without '-'",
  StringRes.phoneNumberError: "please enter a valid phone number",
  StringRes.name: "Name",
  StringRes.nameError: "2자리 이상 이름을 입력해주세요.",
  StringRes.nameHint: "Enter your name",
  StringRes.findIdResult: "@name님의 아이디는\n@email 입니다.",
  StringRes.changePassword: "비밀번호 재설정",
  StringRes.category: "Category",
  StringRes.sports: "Sport",
  StringRes.clickToSelect: "Tap to select",
  StringRes.amateur: "Amateur",
  StringRes.elite: "Elite",
  StringRes.selectCategory: "Select Category",
  StringRes.selectSports: "Select Sport",
  StringRes.search: "Search",
  StringRes.select: "Select",
  StringRes.myInformation: "My Information",
  StringRes.teamName: "Team name",
  StringRes.selectTeam: "Tap to select",
  StringRes.height: "Height",
  StringRes.weight: "Weight",
  StringRes.cm: "cm",
  StringRes.kg: "kg",
  StringRes.birth: "Date of birth",
  StringRes.birthHint: "Please enter 8 digits of your date of birth",
  StringRes.gender: "Gender",
  StringRes.male: "Male",
  StringRes.female: "Female",
  StringRes.eightDigits: "8자리",
  StringRes.positionMultipleSelectionPossible:
      "Position (Multiple Selection Available)",
  StringRes.mainFoot: "Preferred Foot",
  StringRes.leftFoot: "Left Foot",
  StringRes.rightFoot: "Right Foot",
  StringRes.registration: "Registration",
  StringRes.confirm: "Confirm",
  StringRes.searchTeams: "Team Search",
  StringRes.logo: "Logo",
  StringRes.clubName: "Team",
  StringRes.dedicatedCoach: "Coach",
  StringRes.sir: "님",
  StringRes.myState: "My state",
  StringRes.noData: "데이터\n없음",
  StringRes.dataNotAvailable: "No Data",
  StringRes.hooperIndex: "HooperIndex",
  StringRes.homeHooperIndexAverage: "HooperIndex\naverage",
  StringRes.hooperIndexAverage: "HooperIndex average",
  StringRes.urinalysis: "Urine color test",
  StringRes.urinalysisAverage: "Urine color test Average",
  StringRes.urinalysisTable: "Chart of urinary",
  StringRes.injuryRisk: "Injury Risk",
  StringRes.workoutIntensity: "Intensity",
  StringRes.workoutIntensityKorEng: "Intensity",
  StringRes.noRecordAndRecordYourStatusToday: "기록가 없습니다. 오늘 상태를 기록하세요!",
  StringRes.emptyWeightParams: "공복 몸무게 : @weightkg",
  StringRes.emptyWeight: "Fasting Weight",
  StringRes.emptyWeightWarning: "수분 섭취 상태와 함께 식단 조절에 신경쓰세요.",
  StringRes.emptyWeightGood: "식단조절에 신경쓰세요.",
  StringRes.workoutIntensityStatistics: "운동 강도 통계",
  StringRes.physical: "Physical",
  StringRes.pleaseSelectCategory: "Please select the category",
  StringRes.monthly: "월간",
  StringRes.weekly: "주간",
  StringRes.sleep: "Sleep quality",
  StringRes.sleepNoSpace: "Sleep quality",
  StringRes.sleepKorEng: "수면의 질(sleep)",
  StringRes.sleepEng: "sleep",
  StringRes.stress: "Stress",
  StringRes.stressKorEng: "스트레스(stress)",
  StringRes.stressEng: "stress",
  StringRes.fatigue: "Fatigue",
  StringRes.fatigueKorEng: "피로(fatigue)",
  StringRes.fatigueEng: "fatigue",
  StringRes.musclePain: "Muscle soreness",
  StringRes.musclePainKorEng: "근육통(muscleSoreness)",
  StringRes.musclePainEng: "muscle soreness",
  StringRes.urineVeryGood: "매우 양호",
  StringRes.urineGood: "양호",
  StringRes.urineAppropriate: "적정",
  StringRes.urineDemand: "수분 섭취 요망",
  StringRes.urineRecommended: "수분 섭취 권장",
  StringRes.urineNeed: "수분 섭취  필요",
  StringRes.urineEmergency: "수분 부족 위급",
  StringRes.urineNone: "정보 없음",
  StringRes.workoutTime: "Exercise time",
  StringRes.todayTime: "오늘의 시간",
  StringRes.trainingBalance: "트레이닝 밸런스",
  StringRes.trainingBalanceFormula: "(운동강도 X 운동시간) 평균 값",
  StringRes.thisWeek: "This week",
  StringRes.lastWeek: "Last week",
  StringRes.lastFourWeek: "지난4주",
  StringRes.lastEightWeek: "지난8주",
  StringRes.unitPercent: "(단위: %)",
  StringRes.informationRegistrationGuide:
      "You need to register\nadditional information\nto use the app",
  StringRes.doInformationRegistration: "Register Information",
  StringRes.wellness: "Wellness",
  StringRes.wellnessKorEng: "웰리니스 (Wellness)",
  StringRes.wellnessDescription:
      "팀 내 피지컬 코치 및 운동코치 또는 선수 개인이 웰리니스 관련 데이터를 수집하고 분석함으로써 운동 컨디션 및 삶의 질을 관리하고, 부상을 보다 효과적으로 예방하는데 도움이 됩니다. 뿐만아니라, 경기력 향상 및 유지하는데 또한 도움이 됩니다.",
  StringRes.injuryManagement: "Injury",
  StringRes.injuryCheck: "Injury Check",
  StringRes.injuryHistory: "부상이력",
  StringRes.injuryHistoryDescription: "완치된 부상을 체크해주세요.",
  StringRes.close: "Close",
  StringRes.open: "Open",
  StringRes.veryVeryGood: "very, very good",
  StringRes.veryVeryBad: "very, very bad",
  StringRes.satisfactory: "양호한",
  StringRes.insufficient: "부족한",
  StringRes.urineTestWeightKg: "Body weight in overnight-fasted (kg)",
  StringRes.myAnswer: "Answer",
  StringRes.bmi: "Body Fat",
  StringRes.bmiPercent: "체지방률(%)",
  StringRes.compellingRequest: "대략적으로 작성해주세요.",
  StringRes.doSave: "Save",
  StringRes.save: "Save",
  StringRes.doUpdate: "수정하기",
  StringRes.hourParams: "@hour시간",
  StringRes.minParams: "@min분",
  StringRes.performedWorkout: "어떤 운동을 했나요?",
  StringRes.sportsTraining: "Sport Training",
  StringRes.physicalTraining: "Physical Training",
  StringRes.intensityLevelVeryEasy: "Very easy",
  StringRes.intensityLevelVeryEasyDescription:
      "Not quite hard but,\nfeeling hard compared\nto the state of relax",
  StringRes.intensityLevelEasy: "Easy",
  StringRes.intensityLevelEasyDescription:
      "I can workout more than\ncouple of hours.\nI can easily breath and have\nconversation with peers\nduring exercise",
  StringRes.intensityLevelNormal: "Intermediate",
  StringRes.intensityLevelNormalDescription:
      "Heavy breathing but, can have short conversation with peers. I still feel comfortable during exercise, but it will be hard if I do work more",
  StringRes.intensityLevelHard: "Hard",
  StringRes.intensityLevelHardDescription:
      "Feeling uncomfortable, but I can still talk with peers in a sentence",
  StringRes.intensityLevelVeryHard: "Very Hard",
  StringRes.intensityLevelVeryHardDescription:
      "Feeling difficult to keep exercise",
  StringRes.intensityLevelOver: "Exhausted\n(more than 100%)",
  StringRes.intensityLevelOverDescription:
      "Can't breath and impossible of keeping conversation",
  StringRes.description: "Description",
  StringRes.intensity: "Intensity",
  StringRes.add: "추가",
  StringRes.injuryTypeContact: "Contact injury",
  StringRes.injuryTypeNonContact: "Non-contact injury",
  StringRes.injuryTypeDisease: "Illness",
  StringRes.injuryTypeContactSimple: "Contact",
  StringRes.injuryTypeNonContactSimple: "Non-contact",
  StringRes.injuryTypeDiseaseSimple: "Illness",
  StringRes.injuryLocationSelection: "Please select the injured area.",
  StringRes.injuryCheckDiseaseHint:
      "Please fill out the details of the injury and the disease.\n(Limited 40 characters)",
  StringRes.front: "Front",
  StringRes.back: "Back",
  StringRes.upperBody: "Upper body",
  StringRes.lowerBody: "Lower body",
  StringRes.leftArm: "Left arm",
  StringRes.rightArm: "Right arm",
  StringRes.leftLeg: "Left limb",
  StringRes.rightLeg: "Right limb",
  StringRes.torso: "Torso",
  StringRes.todayFeedback: "Today's Feedback",
  StringRes.emptyFeedback: "No feedback available.",
  StringRes.monthlySchedule: "Monthly Major Schedule",
  StringRes.todaySchedule: "Today Schedule",
  StringRes.contactDedicatedCoach: "Contact the Dedicated Coach",
  StringRes.field: "Field",
  StringRes.period: "Period",
  StringRes.time: "Time",
  StringRes.place: "Location",
  StringRes.trainingContent: "Training Content",
  StringRes.noSchedule: "No schedule.",
  StringRes.noAccounts: "No registered account found",
  StringRes.snsAccounts: "SNS로 가입한 계정입니다.",
  StringRes.resultOfSignedInId: "This is the result of the subscribed ID",
  StringRes.kakaoUser: "카카오회원",
  StringRes.naverUser: "네이버회원",
  StringRes.appleUser: "애플회원",
  StringRes.changeCompleteAndLogin: "변경완료 후 로그인",
  StringRes.identity: "아이디",
  StringRes.camera: "카메라",
  StringRes.album: "앨범",
  StringRes.detailedMuscle: "Detail Muscle",
  StringRes.painLevel: "State of Pain",
  StringRes.painSymptoms: "Pain pattern (multiple selectable)",
  StringRes.painTiming: "a period of pain",
  StringRes.intermittent: "Intermittent",
  StringRes.regular: "Constancy",
  StringRes.restPeriod: "In relax state",
  StringRes.duringWorkout: "During exercise",
  StringRes.injuryCause: "Injury details",
  StringRes.injuryCauseHint:
      "Please write a more detailed record of the injury.",
  StringRes.noRegisteredTeam:
      "No teams are registered.\nPlease re-register the team.",
  StringRes.teamSelect: "Select Team",
  StringRes.complete: "Complete",
  StringRes.pushSelect: "Tap to select",
  StringRes.teamRequest: "Requesting approval.\nPlease wait a moment.",
  StringRes.weekDaySun: "일",
  StringRes.weekDayMon: "월",
  StringRes.weekDayTue: "화",
  StringRes.weekDayWed: "수",
  StringRes.weekDayThu: "목",
  StringRes.weekDayFri: "금",
  StringRes.weekDaySat: "토",
  StringRes.appleNeedPass: "소셜계정으로 로그인하신 경우 원활한\n이용을 위해 최초 1회의 본인인증이\n필요합니다.",
  StringRes.managementRequired: "관리요망",
  StringRes.injuryLevelVeryHighPain: "Very serious",
  StringRes.injuryLevelHighPain: "Serious",
  StringRes.injuryLevelInjured: "Feel injury",
  StringRes.injuryLevelMildDiscomfort: "Intermediate",
  StringRes.injuryLevelModeratePain: "Light",
  StringRes.injuryLevelNoPain: "No pain",
  StringRes.injuryLevelVeryHighPainDescription: "Need a doctor",
  StringRes.injuryLevelHighPainDescription:
      "Difficult to keep exercise and ordinary movement.",
  StringRes.injuryLevelInjuredDescription:
      "Still feel pain after warming-up, and occurred restriction of performance in specific posture.",
  StringRes.injuryLevelMildDiscomfortDescription:
      "Capable of exericse, but the pain gets better after warming-up.",
  StringRes.injuryLevelModeratePainDescription:
      "Mainly tightness and stiffness",
  StringRes.injuryLevelNoPainDescription: "No restriction of activity",
  StringRes.tingling: "Shooting",
  StringRes.pressure: "Pressure",
  StringRes.weakness: "Lose Force",
  StringRes.numbness: "Numb",
  StringRes.tightness: "Cramp",
  StringRes.postureSensitive: "Sensitive in specific posture",
  StringRes.aching: "Soreness",
  StringRes.stiff: "Tightness",
  StringRes.soreness: "Stiffness",
  StringRes.sharpPain: "Sharp Pain",
  StringRes.radiatingPain: "Spread pain out around the part of injury",
  StringRes.delete: "Delete",
  StringRes.deleteDialog: "Do you want to delete?",
  StringRes.painPosition: "통증위치",
  StringRes.signOut: "Withdraw",
  StringRes.signOutDescription: "Do you want to withdraw?",
  StringRes.doSignOut: "Withdraw",
  StringRes.authCode: "Verification code",
  StringRes.authCodeHint: "Enter the 6-digit verification code",
  StringRes.signUpComplete: "Complete Sign up",
  StringRes.registrationCompletedAfterAdminApproval:
      'Registration will be completed after administrator approval',
  StringRes.writeInBodyRecord: 'Please fill it out roughly.',
  StringRes.injuryRiskVeryGood: '매우좋음',
  StringRes.injuryRiskGood: '좋음',
  StringRes.injuryRiskDangerous: '관리요망',
  StringRes.injuryRiskVeryDangerous: '매우위험',
  StringRes.moistureGood: 'good',
  StringRes.moistureLack: 'shortage',
  StringRes.trainingBalanceNone: '-',
  StringRes.trainingBalanceLess: '부족',
  StringRes.trainingBalanceNormal: '적절',
  StringRes.trainingBalanceOver: '과훈련',
  StringRes.urineWeightLessMoistureGood:
      'You need to get enough nutrition after exercising',
  StringRes.urineWeightLessMoistureBad:
      'Please pay attention to water intake management on a daily basis',
  StringRes.urineWeightGoodMoistureGood: '식단, 수분 섭취 모두 양호합니다.',
  StringRes.urineWeightGoodMoistureBad:
      'You need to get enough water after exercising',
  StringRes.urineWeightOverMoistureGood: 'Pay attention no your diet',
  StringRes.urineWeightOverMoistureBad:
      'Please pay attention to water intake management on a daily basis',
  StringRes.progress: "진행",
  StringRes.proceeding: "진행중",
  StringRes.recovery: "Completed",
  StringRes.recoveryCompleteQuestion: "부상이 완치되었습니까?",
  StringRes.yes: '예',
  StringRes.no: '아니요',
  StringRes.myHistory: 'My History',
  StringRes.historyFilterAll: 'Entire Period',
  StringRes.historyFilterWeek: 'Last 1 Week',
  StringRes.historyFilterMonth: 'Last 1 Month',
  StringRes.historyFilterDesc: 'Most Recent',
  StringRes.historyFilterAsc: 'Oldest',
  StringRes.historyFilterProgressInjury: 'ongoing injury',
  StringRes.historyFilterHealedInjury: 'complete injury',
  StringRes.whatWellness: 'Wellness?',
  StringRes.wellnessGuide:
      'Physical and athletic coaches or individual athletes within the team are wellness-related Manage your exercise condition and quality of life by collecting and analyzing data, It helps prevent injuries more effectively. Not only that, It also helps improve and maintain performance.',
  StringRes.workoutTimeAverage: 'Training duration',
  StringRes.workoutIntensityAverage: 'Training Intensity',
  StringRes.step: 'Stage',
  StringRes.filter: 'Filter',
  StringRes.sortBy: 'Sorting Criteria',
  StringRes.inquiryPeriod: 'Query Period',
  StringRes.todayTraining: 'Today Training',
  StringRes.noRegisteredTrainingToday: 'no registered training today',
  StringRes.beCarefulWorkingOutToday: "Be cautious during today's training!",
  StringRes.moreShow: 'More',
  StringRes.urineState: '소변상태',
  StringRes.injuryCurrentSituation: 'Injury',
  StringRes.risk7LessThan: '새로운 기록을 세워도 되는 컨디션입니다.',
  StringRes.risk7To14: '운동을 위한 적합한 컨디션입니다.',
  StringRes.risk14To21: '운동 시 집중해야 되는 컨디션입니다.',
  StringRes.risk21More: '부상 위험이 매우 높습니다. 운동 강도와 양을 조절하세요.',
  StringRes.drinkingGood: '수분 섭가 잘 이루어져 있습니다.',
  StringRes.drinkingWarning: '수분 섭취에 주의 기울여야 합니다.',
  StringRes.drinkingDanger: '수분 섭취 매우 부족 상태입니다.',
  StringRes.eatingGood: '체중 변화가 양호합니다.',
  StringRes.eatingNeed: '영양 섭취가 필요합니다.',
  StringRes.eatingOver: '음식양 조절이 필요합니다.',
  StringRes.enterIntensityBeforeForget: "잊기 전 운동강도를 등록해주세요.",
  StringRes.cancel: 'Cancel',
  StringRes.waterIntakeStatus: 'Urine Condition',
  StringRes.verify: 'Verify',
  StringRes.reVerify: 'Re-verify',
  StringRes.selectPosition: 'Select position',
  StringRes.duration: 'Duration',
  StringRes.urineColor: 'Urine Color',
  StringRes.bodyFat: 'Body Fat',
  StringRes.drinkGood: 'good',
  StringRes.drinkShortage: 'shortage',
  StringRes.agree: 'Agree',
  StringRes.pleaseChooseWorkout: 'Please choose your workout.',
  StringRes.injuryCheckSaveSuccessful: 'Injury check save successful',
  StringRes.intensitySaveSuccessful: 'Workout intensity save successful',
};

final _enMuscleName =  {
  StringRes.TRAPEZIUS: "TRAPEZIUS",
  StringRes.PECTORALIS_MAJOR: "PECTORALIS_MAJOR",
  StringRes.EXTERNAL_OBLIQUE: "EXTERNAL_OBLIQUE",
  StringRes.RECTUS_ABDOMINIS: "RECTUS_ABDOMINIS",
  StringRes.DELTOID: "DELTOID",
  StringRes.BICEPS: "BICEPS",
  StringRes.BRACHIORADIALIS: "BRACHIORADIALIS",
  StringRes.BRACHIALIS: "BRACHIALIS",
  StringRes.PRONATOR_TERES: "PRONATOR_TERES",
  StringRes.PALMARIS_LONGUS: "PALMARIS_LONGUS",
  StringRes.TRICEPS: "TRICEPS",
  StringRes.TENSOR_FASCIAE_LATAE: "TENSOR_FASCIAE_LATAE",
  StringRes.SARTORIUS: "SARTORIUS",
  StringRes.VASTUS_LATERALIS: "VASTUS_LATERALIS",
  StringRes.RECTUS_FEMORIS: "RECTUS_FEMORIS",
  StringRes.IT_BAND: "IT_BAND",
  StringRes.EXTENSOR_DIGITORUM_LONGUS: "EXTENSOR_DIGITORUM_LONGUS",
  StringRes.TIBIALIS_ANTERIOR: "TIBIALIS_ANTERIOR",
  StringRes.FIBULARIS_LONGUS: "FIBULARIS_LONGUS",
  StringRes.EXTENSOR_HALLUCIS_LONGUS: "EXTENSOR_HALLUCIS_LONGUS",
  StringRes.ILIACUS: "ILIACUS",
  StringRes.PSOAS_MAJOR: "PSOAS_MAJOR",
  StringRes.PECTINEUS: "PECTINEUS",
  StringRes.ADDUCTOR_LONGUS: "ADDUCTOR_LONGUS",
  StringRes.ADDUCTOR_MAGNUS: "ADDUCTOR_MAGNUS",
  StringRes.GRACILIS: "GRACILIS",
  StringRes.VASTUS_MEDIALIS: "VASTUS_MEDIALIS",
  StringRes.VASTUS_INTERMEDIUS: "VASTUS_INTERMEDIUS",
  StringRes.GASTROCNEMIUS: "GASTROCNEMIUS",
  StringRes.SOLEUS: "SOLEUS",
  StringRes.GLUTE: "GLUTE",
  StringRes.CORACOBRACHIALIS: "CORACOBRACHIALIS",
  StringRes.TERES_MINOR: "TERES_MINOR",
  StringRes.TERES_MAJOR: "TERES_MAJOR",
  StringRes.LATISSIMUS_DORSI: "LATISSIMUS_DORSI",
  StringRes.ERECTOR_SPRINAE: "ERECTOR_SPRINAE",
  StringRes.EXTENSOR_CARPI_RADIALIS_LONGUS: "EXTENSOR_CARPI_RADIALIS_LONGUS",
  StringRes.EXTENSOR_DIGITORUM: "EXTENSOR_DIGITORUM",
  StringRes.ANCONEUS: "ANCONEUS",
  StringRes.EXTENSOR_CARPI_ULNARIS: "EXTENSOR_CARPI_ULNARIS",
  StringRes.BICEPS_FEMORIS: "BICEPS_FEMORIS",
  StringRes.SEMIMEMBRANOSUS: "SEMIMEMBRANOSUS",
};
