part of 'translations.dart';


final _koMuscleName = {
  StringRes.TRAPEZIUS: "승모근",
  StringRes.PECTORALIS_MAJOR: "대흉근",
  StringRes.EXTERNAL_OBLIQUE: "외복사근",
  StringRes.RECTUS_ABDOMINIS: "복직근",
  StringRes.DELTOID: "삼각근",
  StringRes.BICEPS: "이두근",
  StringRes.BRACHIORADIALIS: "완요골근",
  StringRes.BRACHIALIS: "상완근",
  StringRes.PRONATOR_TERES: "원회내근",
  StringRes.PALMARIS_LONGUS: "장장근",
  StringRes.TRICEPS: "삼두근",
  StringRes.TENSOR_FASCIAE_LATAE: "대퇴근막장근",
  StringRes.SARTORIUS: "봉공근",
  StringRes.VASTUS_LATERALIS: "외측광근",
  StringRes.RECTUS_FEMORIS: "대퇴직근",
  StringRes.IT_BAND: "장경인대",
  StringRes.EXTENSOR_DIGITORUM_LONGUS: "장지신근",
  StringRes.TIBIALIS_ANTERIOR: "전경골근",
  StringRes.FIBULARIS_LONGUS: "장비골근",
  StringRes.EXTENSOR_HALLUCIS_LONGUS: "장모지신근",
  StringRes.ILIACUS: "장골근",
  StringRes.PSOAS_MAJOR: "대요근",
  StringRes.PECTINEUS: "치골근",
  StringRes.ADDUCTOR_LONGUS: "장내전근",
  StringRes.ADDUCTOR_MAGNUS: "대내전근",
  StringRes.GRACILIS: "박근",
  StringRes.VASTUS_MEDIALIS: "내측광근",
  StringRes.VASTUS_INTERMEDIUS: "중간광근",
  StringRes.GASTROCNEMIUS: "비복근",
  StringRes.SOLEUS: "가자미근",
  StringRes.GLUTE: "둔근",
  StringRes.CORACOBRACHIALIS: "오훼완근",
  StringRes.TERES_MINOR: "소원근",
  StringRes.TERES_MAJOR: "대원근",
  StringRes.LATISSIMUS_DORSI: "광배근",
  StringRes.ERECTOR_SPRINAE: "척추기립근",
  StringRes.EXTENSOR_CARPI_RADIALIS_LONGUS: "요측수근신근",
  StringRes.EXTENSOR_DIGITORUM: "총지신근",
  StringRes.ANCONEUS: "주근",
  StringRes.EXTENSOR_CARPI_ULNARIS: "척측수근신근",
  StringRes.BICEPS_FEMORIS: "대퇴이두근",
  StringRes.SEMIMEMBRANOSUS: "반건반막양근",
};

/// 한국어.
final koKr = {
  ..._koMuscleName,
  StringRes.appName: "Physical Note",
  StringRes.serverError: '서버 에러',
  StringRes.notification: "알림",
  StringRes.message: "메시지",
  StringRes.messageChannelDescription: "메시지 알림",
  StringRes.bottomTabHistory: "이력",
  StringRes.bottomTabHome: "홈",
  StringRes.bottomTabFeedback: "피드백",
  StringRes.email: "이메일",
  StringRes.emailHint: "이메일 주소를 입력하세요.",
  StringRes.emailError: "바른 이메일 양식을 입력해주세요.",
  StringRes.emailDuplicated: "중복된 이메일입니다.",
  StringRes.password: "비밀번호",
  StringRes.passwordHint: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordError: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordConfirm: "비밀번호 확인",
  StringRes.passwordNotMatched: "비밀번호가 일치하지 않습니다.",
  StringRes.simpleSignUp: "간편 회원가입",
  StringRes.findId: "아이디 찾기",
  StringRes.findPw: "비밀번호 찾기",
  StringRes.login: "로그인",
  StringRes.logout: "로그아웃",
  StringRes.startWithSns: "SNS 계정으로 시작하기",
  StringRes.acceptTerms: "서비스 이용을 위해\n약관에 동의해주세요.",
  StringRes.allAgree: "전체 동의",
  StringRes.requiredTermService: "[필수] 서비스 이용약관",
  StringRes.requiredTermPrivacy: "[필수] 개인정보 수집 및 이용 동의",
  StringRes.next: "다음",
  StringRes.prev: "이전",
  StringRes.signUp: "회원가입",
  StringRes.phoneNumber: "휴대폰 번호",
  StringRes.phoneHint: "( - )없이 11자리를 입력하세요.",
  StringRes.phoneNumberError: "올바른 전화번호를 입력해주세요.",
  StringRes.name: "이름",
  StringRes.nameError: "2자리 이상 이름을 입력해주세요.",
  StringRes.nameHint: "이름을 입력하세요.",
  StringRes.findIdResult: "@name님의 아이디는\n@email 입니다.",
  StringRes.changePassword: "비밀번호 재설정",
  StringRes.category: "종목",
  StringRes.sports: "스포츠",
  StringRes.clickToSelect: "눌러 선택하세요.",
  StringRes.amateur: "아마추어",
  StringRes.elite: "엘리트",
  StringRes.selectCategory: "종목 선택",
  StringRes.selectSports: "스포츠 선택",
  StringRes.search: "검색",
  StringRes.select: "선택",
  StringRes.myInformation: "내정보",
  StringRes.teamName: "팀명",
  StringRes.selectTeam: "소속된 팀명을 선택해주세요.",
  StringRes.height: "키",
  StringRes.weight: "몸무게",
  StringRes.cm: "cm",
  StringRes.kg: "kg",
  StringRes.birth: "생년월일",
  StringRes.birthHint: "생년월일 8자리를 입력해주세요.",
  StringRes.gender: "성별",
  StringRes.male: "남자",
  StringRes.female: "여자",
  StringRes.eightDigits: "8자리",
  StringRes.positionMultipleSelectionPossible: "포지션(다중선택가능)",
  StringRes.mainFoot: "주 발",
  StringRes.leftFoot: "왼쪽 발",
  StringRes.rightFoot: "오른쪽 발",
  StringRes.registration: "등록",
  StringRes.confirm: "확인",
  StringRes.searchTeams: "팀 검색",
  StringRes.logo: "로고",
  StringRes.clubName: "구단이름",
  StringRes.dedicatedCoach: "전담코치",
  StringRes.sir: "님",
  StringRes.myState: "나의 상태",
  StringRes.noData: "데이터\n없음",
  StringRes.dataNotAvailable: "데이터가 없습니다.",
  StringRes.hooperIndex: "후퍼인댁스",
  StringRes.homeHooperIndexAverage: "후퍼인댁스 평균",
  StringRes.hooperIndexAverage: "후퍼인댁스 평균",
  StringRes.urinalysis: "소변검사",
  StringRes.urinalysisAverage: "소변검사 평균",
  StringRes.urinalysisTable: "소변검사표",
  StringRes.injuryRisk: "부상위험도",
  StringRes.workoutIntensity: "운동강도",
  StringRes.workoutIntensityKorEng: "운동강도(Intensity)",
  StringRes.noRecordAndRecordYourStatusToday: "기록가 없습니다. 오늘 상태를 기록하세요!",
  StringRes.emptyWeightParams: "공복 몸무게 : @weightkg",
  StringRes.emptyWeight: "공복몸무게",
  StringRes.emptyWeightWarning: "수분 섭취 상태와 함께 식단 조절에 신경쓰세요.",
  StringRes.emptyWeightGood: "식단조절에 신경쓰세요.",
  StringRes.workoutIntensityStatistics: "운동 강도 통계",
  StringRes.physical: "피지컬",
  StringRes.pleaseSelectCategory: "종목을 선택해주세요.",
  StringRes.monthly: "월간",
  StringRes.weekly: "주간",
  StringRes.sleep: "수면의 질",
  StringRes.sleepNoSpace: "수면의질",
  StringRes.sleepKorEng: "수면의 질(sleep)",
  StringRes.sleepEng: "sleep",
  StringRes.stress: "스트레스",
  StringRes.stressKorEng: "스트레스(stress)",
  StringRes.stressEng: "stress",
  StringRes.fatigue: "피로",
  StringRes.fatigueKorEng: "피로(fatigue)",
  StringRes.fatigueEng: "fatigue",
  StringRes.musclePain: "근육통",
  StringRes.musclePainKorEng: "근육통(muscleSoreness)",
  StringRes.musclePainEng: "muscleSoreness",
  StringRes.urineVeryGood: "매우 양호",
  StringRes.urineGood: "양호",
  StringRes.urineAppropriate: "적정",
  StringRes.urineDemand: "수분 섭취 요망",
  StringRes.urineRecommended: "수분 섭취 권장",
  StringRes.urineNeed: "수분 섭취  필요",
  StringRes.urineEmergency: "수분 부족 위급",
  StringRes.urineNone: "정보 없음",
  StringRes.workoutTime: "운동시간",
  StringRes.todayTime: "오늘의 시간",
  StringRes.trainingBalance: "트레이닝 밸런스",
  StringRes.trainingBalanceFormula: "(운동강도 X 운동시간) 평균 값",
  StringRes.thisWeek: "이번주",
  StringRes.lastWeek: "저번주",
  StringRes.lastFourWeek: "지난4주",
  StringRes.lastEightWeek: "지난8주",
  StringRes.unitPercent: "(단위: %)",
  StringRes.informationRegistrationGuide: "추가정보를 등록해야만\n앱을 사용할 수 있습니다.",
  StringRes.doInformationRegistration: "정보등록 하기",
  StringRes.wellness: "웰니스",
  StringRes.wellnessKorEng: "웰니스 (Wellness)",
  StringRes.wellnessDescription:
      "팀 내 피지컬 코치 및 운동코치 또는 선수 개인이 웰니스 관련 데이터를 수집하고 분석함으로써 운동 컨디션 및 삶의 질을 관리하고, 부상을 보다 효과적으로 예방하는데 도움이 됩니다. 뿐만아니라, 경기력 향상 및 유지하는데 또한 도움이 됩니다.",
  StringRes.injuryManagement: "부상관리",
  StringRes.injuryCheck: "부상체크",
  StringRes.injuryHistory: "부상이력",
  StringRes.injuryHistoryDescription: "완치된 부상을 체크해주세요.",
  StringRes.close: "닫기",
  StringRes.open: "열기",
  StringRes.veryVeryGood: "매우, 매우 좋은",
  StringRes.veryVeryBad: "매우, 매우 나쁜",
  StringRes.satisfactory: "양호한",
  StringRes.insufficient: "부족한",
  StringRes.urineTestWeightKg: "소변 검사 직후 공복 상태 몸무게 (kg)",
  StringRes.myAnswer: "내 답변",
  StringRes.bmi: "체지방",
  StringRes.bmiPercent: "체지방률(%)",
  StringRes.compellingRequest: "대략적으로 작성해주세요.",
  StringRes.doSave: "저장하기",
  StringRes.save: "저장",
  StringRes.doUpdate: "수정하기",
  StringRes.hourParams: "@hour시간",
  StringRes.minParams: "@min분",
  StringRes.performedWorkout: "어떤 운동을 했나요?",
  StringRes.sportsTraining: "스포츠훈련",
  StringRes.physicalTraining: "피지컬훈련",
  StringRes.intensityLevelVeryEasy: "매우 쉬움",
  StringRes.intensityLevelVeryEasyDescription: "힘들진 않지만\n쉴때보다는 힘듦",
  StringRes.intensityLevelEasy: "쉬움",
  StringRes.intensityLevelEasyDescription: "몇시간은 운동\n더 할 수 있음\n숨쉬기 쉽고\n대화가 가능",
  StringRes.intensityLevelNormal: "중간",
  StringRes.intensityLevelNormalDescription:
      "숨이 거칠고,\n짧은 대화가\n가능함. 편안\n하지만 더하면\n힘들 것 같음",
  StringRes.intensityLevelHard: "힘듦",
  StringRes.intensityLevelHardDescription: "불편은 하지만\n문장으로 말할\n수 있음",
  StringRes.intensityLevelVeryHard: "매우 힘듦",
  StringRes.intensityLevelVeryHardDescription: "운동강도를\n유지하기 어려움",
  StringRes.intensityLevelOver: "100%이상",
  StringRes.intensityLevelOverDescription: "숨을 쉴 수 없음\n대화불가능",
  StringRes.description: "설명",
  StringRes.intensity: "강도",
  StringRes.add: "추가",
  StringRes.injuryTypeContact: "접촉(타박상)",
  StringRes.injuryTypeNonContact: "비접촉(오버트레이닝)",
  StringRes.injuryTypeDisease: "질병",
  StringRes.injuryTypeContactSimple: "접촉(타박상)",
  StringRes.injuryTypeNonContactSimple: "비접촉(오버트레이닝)",
  StringRes.injuryTypeDiseaseSimple: "질병",
  StringRes.injuryLocationSelection: "부상 부위를 선택해주세요.",
  StringRes.injuryCheckDiseaseHint: "부상 경위 및 질병 내용을 작성 해주세요.\n(글자수 제한 40자)",
  StringRes.front: "앞",
  StringRes.back: "뒤",
  StringRes.upperBody: "상체",
  StringRes.lowerBody: "하체",
  StringRes.leftArm: "왼팔",
  StringRes.rightArm: "오른팔",
  StringRes.leftLeg: "왼쪽다리",
  StringRes.rightLeg: "오른쪽다리",
  StringRes.torso: "몸통",
  StringRes.todayFeedback: "오늘의 피드백",
  StringRes.emptyFeedback: "피드백이 없습니다.",
  StringRes.monthlySchedule: "월간 주요 일정",
  StringRes.todaySchedule: "오늘 일정",
  StringRes.contactDedicatedCoach: "전담코치에게 연락하기",
  StringRes.field: "필드",
  StringRes.period: "기간",
  StringRes.time: "시간",
  StringRes.place: "장소",
  StringRes.trainingContent: "훈련내용",
  StringRes.noSchedule: "일정이 없습니다.",
  StringRes.noAccounts: "기입된 계정이 없습니다.",
  StringRes.snsAccounts: "SNS로 가입한 계정입니다.",
  StringRes.resultOfSignedInId: "로 가입한 아이디 결과입니다.",
  StringRes.kakaoUser: "카카오회원",
  StringRes.naverUser: "네이버회원",
  StringRes.appleUser: "애플회원",
  StringRes.changeCompleteAndLogin: "변경완료 후 로그인",
  StringRes.identity: "아이디",
  StringRes.camera: "카메라",
  StringRes.album: "앨범",
  StringRes.detailedMuscle: "상세 근육",
  StringRes.painLevel: "통증정도",
  StringRes.painSymptoms: "통증 양상 (다수선택가능)",
  StringRes.painTiming: "통증시기",
  StringRes.intermittent: "간헐적",
  StringRes.regular: "일정함",
  StringRes.restPeriod: "휴식기",
  StringRes.duringWorkout: "운동중",
  StringRes.injuryCause: "부상경위",
  StringRes.injuryCauseHint: "부상에 대한 기록을 더 자세히 작성 해주세요.",
  StringRes.noRegisteredTeam: "등록된 팀이 없습니다.\n팀을 재등록 해주세요.",
  StringRes.teamSelect: "팀 선택하기",
  StringRes.complete: "완료",
  StringRes.pushSelect: "눌러서 선택하세요.",
  StringRes.teamRequest: "승인요청 중 입니다.\n잠시만 기다려 주세요.",
  StringRes.weekDaySun: "일",
  StringRes.weekDayMon: "월",
  StringRes.weekDayTue: "화",
  StringRes.weekDayWed: "수",
  StringRes.weekDayThu: "목",
  StringRes.weekDayFri: "금",
  StringRes.weekDaySat: "토",
  StringRes.appleNeedPass: "소셜계정으로 로그인하신 경우 원활한\n이용을 위해 최초 1회의 본인인증이\n필요합니다.",
  StringRes.managementRequired: "관리요망",
  StringRes.injuryLevelInjured: "부상 상태",
  StringRes.injuryLevelVeryHighPain: "매우 심한 통증",
  StringRes.injuryLevelHighPain: "심한 통증",
  StringRes.injuryLevelModeratePain: "보통 통증",
  StringRes.injuryLevelMildDiscomfort: "가벼운 통증",
  StringRes.injuryLevelNoPain: "통증 없음",

  StringRes.injuryLevelInjuredDescription: "의료 상담 필요",
  StringRes.injuryLevelVeryHighPainDescription: "운동 또는 일상 동작이 어려움",
  StringRes.injuryLevelHighPainDescription: "워밍업 후에도 지속, 특정 동작에서 제한 발생",
  StringRes.injuryLevelModeratePainDescription:
      "활동 가능, 하지만 땀이 나거나 열을 내면 통증 완화 가능",
  StringRes.injuryLevelMildDiscomfortDescription: "주로 뻣뻣함과 뻐근함이 느껴짐",
  StringRes.injuryLevelNoPainDescription: "활동 제약 없음",
  StringRes.tingling: "찌릿함",
  StringRes.pressure: "압박감",
  StringRes.weakness: "힘이 빠짐",
  StringRes.numbness: "저리거나 둔해짐",
  StringRes.tightness: "뭉치거나 올라올 것 같은",
  StringRes.postureSensitive: "특정자세에 민감",
  StringRes.aching: "쑤시는",
  StringRes.stiff: "타이트",
  StringRes.soreness: "뻐근함",
  StringRes.sharpPain: "날카로운 통증",
  StringRes.radiatingPain: "통증이 주변으로 확산",
  StringRes.delete: "삭제",
  StringRes.deleteDialog: "삭제하시겠습니까?",
  StringRes.painPosition: "통증위치",
  StringRes.signOut: "탈퇴",
  StringRes.signOutDescription: "탈퇴하시겠습니까?",
  StringRes.doSignOut: "탈퇴하기",
  StringRes.authCode: "인증번호",
  StringRes.authCodeHint: "인증번호 6자리를 입력해주세요.",
  StringRes.signUpComplete: "가입완료",
  StringRes.registrationCompletedAfterAdminApproval: '관리자 승인 후 등록이 완료됩니다.',
  StringRes.writeInBodyRecord: '인바디 기록을 적어주세요.',
  StringRes.injuryRiskVeryGood: '매우좋음',
  StringRes.injuryRiskGood: '좋음',
  StringRes.injuryRiskDangerous: '관리요망',
  StringRes.injuryRiskVeryDangerous: '매우위험',
  StringRes.moistureGood: '수분 양호',
  StringRes.moistureLack: '수분 부족',
  StringRes.trainingBalanceNone: '-',
  StringRes.trainingBalanceLess: '부족',
  StringRes.trainingBalanceNormal: '적절',
  StringRes.trainingBalanceOver: '과훈련',
  StringRes.urineWeightLessMoistureGood: '운동 후 충분한 영양 섭취가 필요합니다.',
  StringRes.urineWeightLessMoistureBad: '평상시 수분 섭취 관리에 신경쓰시길 바랍니다.',
  StringRes.urineWeightGoodMoistureGood: '식단, 수분 섭취 모두 양호합니다.',
  StringRes.urineWeightGoodMoistureBad: '운동 후 충분한 수분 섭취가 필요합니다.',
  StringRes.urineWeightOverMoistureGood: '식단 조절에 신경쓰세요.',
  StringRes.urineWeightOverMoistureBad: '식단 조절과 수분 섭취에 신경쓰세요.',
  StringRes.progress: "진행",
  StringRes.proceeding: "진행중",
  StringRes.recovery: "완치",
  StringRes.recoveryCompleteQuestion: "부상이 완치되었습니까?",
  StringRes.yes: '예',
  StringRes.no: '아니요',
  StringRes.myHistory: '나의 이력',
  StringRes.historyFilterAll: '전체',
  StringRes.historyFilterWeek: '최근 일주일',
  StringRes.historyFilterMonth: '최근 한달',
  StringRes.historyFilterDesc: '최근 순',
  StringRes.historyFilterAsc: '오래된 순',
  StringRes.historyFilterProgressInjury: '진행중인 부상',
  StringRes.historyFilterHealedInjury: '완치된부상',
  StringRes.whatWellness: '웰니스란?',
  StringRes.wellnessGuide:
      '팀 내 피지컬 코치 및 운동코치 또는 선수 개인이 웰니스 관련 데이터를 수집하고 분석함으로써 운동 컨디션 및 삶의 질을 관리하고, 부상을 보다 효과적으로 예방하는데 도움이 됩니다. 뿐만아니라, 경기력 향상 및 유지하는데 또한 도움이 됩니다.',
  StringRes.workoutTimeAverage: '운동시간 평균',
  StringRes.workoutIntensityAverage: '운동강도 평균',
  StringRes.step: '단계',
  StringRes.filter: '필터',
  StringRes.sortBy: '정렬기준',
  StringRes.inquiryPeriod: '조회 기간',
  StringRes.todayTraining: '오늘의 훈련',
  StringRes.noRegisteredTrainingToday: '오늘 등록된 훈련이 없습니다.',
  StringRes.beCarefulWorkingOutToday: '오늘 운동할때 주의하세요!',
  StringRes.moreShow: '더보기',
  StringRes.urineState: '소변상태',
  StringRes.injuryCurrentSituation: '부상현황',
  StringRes.risk7LessThan: '새로운 기록을 세워도 되는 컨디션입니다.',
  StringRes.risk7To14: '운동을 위한 적합한 컨디션입니다.',
  StringRes.risk14To21: '운동 시 집중해야 되는 컨디션입니다.',
  StringRes.risk21More: '부상 위험이 매우 높습니다. 운동 강도와 양을 조절하세요.',
  StringRes.drinkingGood: '수분 섭가 잘 이루어져 있습니다.',
  StringRes.drinkingWarning: '수분 섭취에 주의 기울여야 합니다.',
  StringRes.drinkingDanger: '수분 섭취 매우 부족 상태입니다.',
  StringRes.eatingGood: '체중 변화가 양호합니다.',
  StringRes.eatingNeed: '영양 섭취가 필요합니다.',
  StringRes.eatingOver: '음식양 조절이 필요합니다.',
  StringRes.enterIntensityBeforeForget: "잊기 전 운동강도를 등록해주세요.",
  StringRes.cancel: '취소',
  StringRes.waterIntakeStatus: '수분 섭취 상태',
  StringRes.verify: '인증',
  StringRes.reVerify: '재인증',
  StringRes.selectPosition: '포지션 선택',
  StringRes.duration: '시간',
  StringRes.urineColor: '수분평균',
  StringRes.bodyFat: '체지방률',
  StringRes.drinkGood: '양호',
  StringRes.drinkShortage: '부족',
  StringRes.agree: '다음',
  StringRes.pleaseChooseWorkout: '운동을 선택해주세요.',
  StringRes.injuryCheckSaveSuccessful: '부상 체크 저장 성공',
  StringRes.intensitySaveSuccessful: '운동 강도 저장 성공',
  StringRes.wellnessSaveSuccessful: '웰니스 저장 성공',
};
