part of 'translations.dart';

/// 한국어.
final koKr = {
  StringRes.appName: "Physical Note",
  StringRes.email: "이메일",
  StringRes.emailHint: "이메일 주소를 입력하세요.",
  StringRes.emailError: "바른 이메일 양식을 입력해주세요.",
  StringRes.password: "비밀번호",
  StringRes.passwordHint: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordError: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordConfirm: "비밀번호 확인",
  StringRes.passwordNotMatched: "비밀번호가 일치하지 않습니다.",
  StringRes.simpleSignUp: "간편 회원가입",
  StringRes.findId: "아이디 찾기",
  StringRes.findPw: "비밀번호 찾기",
  StringRes.login: "로그인",
  StringRes.startWithSns: "SNS 계정으로 시작하기",
  StringRes.acceptTerms: "서비스 이용을 위해\n약관에 동의해주세요.",
  StringRes.allAgree: "전체 동의",
  StringRes.requiredTermService: "[필수] 서비스 이용약관",
  StringRes.requiredTermPrivacy: "[필수] 개인정보 수집 및 이용 동의",
  StringRes.next: "다음",
  StringRes.signUp: "회원가입",
  StringRes.phoneNumber: "휴대폰 번호",
  StringRes.phoneHint: "( - )없이 11자리를 입력하세요.",
  StringRes.phoneNumberError: "올바른 전화번호를 입력해주세요.",
  StringRes.name: "이름",
  StringRes.nameError: "2자리 이상 이름을 입력해주세요.",
  StringRes.nameHint: "이름을 입력하세요.",
  StringRes.findIdResult: "@name님의 아이디는\n@email 입니다.",
  StringRes.changePassword: "비밀번호 재설정",
  StringRes.category: "종목",
  StringRes.sports: "스포츠",
  StringRes.clickToSelect: "눌러 선택하세요.",
  StringRes.amateur: "아마추어",
  StringRes.elite: "엘리트",
  StringRes.selectCategory: "종목 선택",
  StringRes.selectSports: "스포츠 선택",
  StringRes.search: "검색",
  StringRes.select: "선택",
  StringRes.myInformation: "내정보",
  StringRes.teamName: "팀명",
  StringRes.selectTeam: "소속된 팀명을 선택해주세요.",
  StringRes.height: "키",
  StringRes.weight: "몸무게",
  StringRes.cm: "cm",
  StringRes.kg: "kg",
  StringRes.birth: "생년월일",
  StringRes.gender: "성별",
  StringRes.eightDigits: "8자리",
  StringRes.positionMultipleSelectionPossible: "포지션(다중선택가능)",
  StringRes.mainFoot: "주 발",
  StringRes.leftFoot: "왼쪽 발",
  StringRes.rightFoot: "오른쪽 발",
  StringRes.registration: "등록",
  StringRes.confirm: "확인",
  StringRes.searchTeams: "팀 검색",
  StringRes.logo: "로고",
  StringRes.clubName: "구단이름",
  StringRes.dedicatedCoach: "전담코치",
  StringRes.sir: "님",
  StringRes.myState: "나의 상태",
  StringRes.noData: "데이터\n없음",
  StringRes.hooperIndex: "후퍼인덱스",
  StringRes.urinalysis: "소변검사",
  StringRes.injuryRisk: "부상위험도",
  StringRes.workoutIntensity: "운동강도",
  StringRes.noRecordAndRecordYourStatusToday: "기록가 없습니다. 오늘 상태를 기록하세요!",
  StringRes.emptyWeightParams: "공복 몸무게 : @weightkg",
  StringRes.emptyWeightWarning: "✔ 수분 섭취 상태와 함께 식단 조절에 신경쓰세요.",
  StringRes.emptyWeightGood: "✔ 식단조절에 신경쓰세요.",
  StringRes.workoutIntensityStatistics: "운동 강도 통계",
  StringRes.physical: "피지컬",
};
