part of 'translations.dart';

/// 한국어.
final koKr = {
  StringRes.appName: "Physical Note",
  StringRes.bottomTabData: "데이터",
  StringRes.bottomTabHome: "홈",
  StringRes.bottomTabFeedback: "피드백",
  StringRes.email: "이메일",
  StringRes.emailHint: "이메일 주소를 입력하세요.",
  StringRes.emailError: "바른 이메일 양식을 입력해주세요.",
  StringRes.emailDuplicated: "중복된 이메일입니다.",
  StringRes.password: "비밀번호",
  StringRes.passwordHint: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordError: "영문+특수문자+숫자를 포함한 8자 이상",
  StringRes.passwordConfirm: "비밀번호 확인",
  StringRes.passwordNotMatched: "비밀번호가 일치하지 않습니다.",
  StringRes.simpleSignUp: "간편 회원가입",
  StringRes.findId: "아이디 찾기",
  StringRes.findPw: "비밀번호 찾기",
  StringRes.login: "로그인",
  StringRes.logout: "로그아웃",
  StringRes.startWithSns: "SNS 계정으로 시작하기",
  StringRes.acceptTerms: "서비스 이용을 위해\n약관에 동의해주세요.",
  StringRes.allAgree: "전체 동의",
  StringRes.requiredTermService: "[필수] 서비스 이용약관",
  StringRes.requiredTermPrivacy: "[필수] 개인정보 수집 및 이용 동의",
  StringRes.next: "다음",
  StringRes.prev: "이전",
  StringRes.signUp: "회원가입",
  StringRes.phoneNumber: "휴대폰 번호",
  StringRes.phoneHint: "( - )없이 11자리를 입력하세요.",
  StringRes.phoneNumberError: "올바른 전화번호를 입력해주세요.",
  StringRes.name: "이름",
  StringRes.nameError: "2자리 이상 이름을 입력해주세요.",
  StringRes.nameHint: "이름을 입력하세요.",
  StringRes.findIdResult: "@name님의 아이디는\n@email 입니다.",
  StringRes.changePassword: "비밀번호 재설정",
  StringRes.category: "종목",
  StringRes.sports: "스포츠",
  StringRes.clickToSelect: "눌러 선택하세요.",
  StringRes.amateur: "아마추어",
  StringRes.elite: "엘리트",
  StringRes.selectCategory: "종목 선택",
  StringRes.selectSports: "스포츠 선택",
  StringRes.search: "검색",
  StringRes.select: "선택",
  StringRes.myInformation: "내정보",
  StringRes.teamName: "팀명",
  StringRes.selectTeam: "소속된 팀명을 선택해주세요.",
  StringRes.height: "키",
  StringRes.weight: "몸무게",
  StringRes.cm: "cm",
  StringRes.kg: "kg",
  StringRes.birth: "생년월일",
  StringRes.gender: "성별",
  StringRes.eightDigits: "8자리",
  StringRes.positionMultipleSelectionPossible: "포지션(다중선택가능)",
  StringRes.mainFoot: "주 발",
  StringRes.leftFoot: "왼쪽 발",
  StringRes.rightFoot: "오른쪽 발",
  StringRes.registration: "등록",
  StringRes.confirm: "확인",
  StringRes.searchTeams: "팀 검색",
  StringRes.logo: "로고",
  StringRes.clubName: "구단이름",
  StringRes.dedicatedCoach: "전담코치",
  StringRes.sir: "님",
  StringRes.myState: "나의 상태",
  StringRes.noData: "데이터\n없음",
  StringRes.hooperIndex: "후퍼인덱스",
  StringRes.urinalysis: "소변검사",
  StringRes.urinalysisTable: "소변검사표",
  StringRes.injuryRisk: "부상위험도",
  StringRes.workoutIntensity: "운동강도",
  StringRes.workoutIntensityKorEng: "운동강도(Intensity)",
  StringRes.noRecordAndRecordYourStatusToday: "기록가 없습니다. 오늘 상태를 기록하세요!",
  StringRes.emptyWeightParams: "공복 몸무게 : @weightkg",
  StringRes.emptyWeightWarning: "✔ 수분 섭취 상태와 함께 식단 조절에 신경쓰세요.",
  StringRes.emptyWeightGood: "✔ 식단조절에 신경쓰세요.",
  StringRes.workoutIntensityStatistics: "운동 강도 통계",
  StringRes.physical: "피지컬",
  StringRes.pleaseSelectCategory: "종목을 선택해주세요.",
  StringRes.monthly: "월간",
  StringRes.weekly: "주간",
  StringRes.sleep: "수면의 질",
  StringRes.sleepKorEng: "수면의 질(sleep)",
  StringRes.sleepEng: "sleep",
  StringRes.stress: "스트레스",
  StringRes.stressKorEng: "스트레스(stress)",
  StringRes.stressEng: "stress",
  StringRes.fatigue: "피로",
  StringRes.fatigueKorEng: "피로(fatigue)",
  StringRes.fatigueEng: "fatigue",
  StringRes.musclePain: "근육통",
  StringRes.musclePainKorEng: "근육통(muscleSoreness)",
  StringRes.musclePainEng: "muscleSoreness",
  StringRes.urineVeryGood: "매우 양호",
  StringRes.urineGood: "양호",
  StringRes.urineAppropriate: "적정",
  StringRes.urineDemand: "수분 섭취 요망",
  StringRes.urineRecommended: "수분 섭취 권장",
  StringRes.urineNeed: "수분 섭취  필요",
  StringRes.urineEmergency: "수분 부족 위급",
  StringRes.urineNone: "정보 없음",
  StringRes.workoutTime: "운동시간",
  StringRes.todayTime: "오늘의 시간",
  StringRes.trainingBalance: "트레이닝 밸런스",
  StringRes.trainingBalanceFormula: "(운동강도 X 운동시간) 평균 값",
  StringRes.thisWeek: "이번주",
  StringRes.lastWeek: "저번주",
  StringRes.lastFourWeek: "지난4주",
  StringRes.lastEightWeek: "지난8주",
  StringRes.unitPercent: "(단위: %)",
  StringRes.informationRegistrationGuide: "추가정보를 등록해야만\n앱을 사용할 수 있습니다.",
  StringRes.doInformationRegistration: "정보등록 하기",
  StringRes.wellness: "웰리니스",
  StringRes.wellnessKorEng: "웰리니스 (Wellness)",
  StringRes.wellnessDescription:
      "팀 내 피지컬 코치 및 운동코치 또는 선수 개인이 웰리니스 관련 데이터를 수집하고 분석함으로써 운동 컨디션 및 삶의 질을 관리하고, 부상을 보다 효과적으로 예방하는데 도움이 됩니다. 뿐만아니라, 경기력 향상 및 유지하는데 또한 도움이 됩니다.",
  StringRes.injuryCheck: "부상체크",
  StringRes.close: "닫기",
  StringRes.open: "열기",
  StringRes.veryVeryGood: "매우, 매우 좋은",
  StringRes.veryVeryBad: "매우, 매우 나쁜",
  StringRes.satisfactory: "양호한",
  StringRes.insufficient: "부족한",
  StringRes.urineTestWeightKg: "소변 검사 직후 공복 상태 몸무게 (kg)",
  StringRes.myAnswer: "내 답변",
  StringRes.bmiPercent: "체지방률(%)",
  StringRes.compellingRequest: "대략적으로 작성해주세요.",
  StringRes.doSave: "저장하기",
  StringRes.save: "저장",
  StringRes.doUpdate: "수정하기",
  StringRes.hourParams: "@hour시간",
  StringRes.minParams: "@min분",
  StringRes.performedWorkout: "어떤 운동을 했나요?",
  StringRes.sportsTraining: "스포츠훈련",
  StringRes.physicalTraining: "피지컬훈련",
  StringRes.intensityLevelVeryEasy: "매우 쉬움",
  StringRes.intensityLevelVeryEasyDescription: "힘들진 않지만 쉴때보다는 힘듦",
  StringRes.intensityLevelEasy: "쉬움",
  StringRes.intensityLevelEasyDescription: "몇시간은 운동 더 할 수 있음 숨쉬기 쉽고 대화가 가능",
  StringRes.intensityLevelNormal: "중간",
  StringRes.intensityLevelNormalDescription:
      "숨이 거칠고, 짧은 대화가 가능함. 편안 하지만 더하면 힘들 것 같음",
  StringRes.intensityLevelHard: "힘듦",
  StringRes.intensityLevelHardDescription: "불편은 하지만 문장으로 말할 수 있음음",
  StringRes.intensityLevelVeryHard: "매우 힘듦",
  StringRes.intensityLevelVeryHardDescription: "운동강도를 유지하기 어려움",
  StringRes.intensityLevelOver: "100%이상",
  StringRes.intensityLevelOverDescription: "숨을 쉴 수 없음 대화불가능",
  StringRes.description: "설명",
  StringRes.intensity: "강도",
  StringRes.add: "추가",
  StringRes.painCheckLocation: "통증이 있는 곳을 체크해주세요.",
  StringRes.injuryTypeContact: "접촉(타박상)",
  StringRes.injuryTypeNonContact: "비접촉(오버트레이닝)",
  StringRes.injuryTypeDisease: "질병",
  StringRes.injuryLocationSelection: "부상 부위를 선택해주세요.",
  StringRes.injuryCheckDiseaseHint: "부상 경위 및 질병 내용을 작성 해주세요.\n(글자수 제한 40자)",
  StringRes.front: "앞",
  StringRes.back: "뒤",
  StringRes.upperBody: "상체",
  StringRes.lowerBody: "하체",
  StringRes.leftArm: "왼팔",
  StringRes.rightArm: "오른팔",
  StringRes.leftLeg: "왼쪽다리",
  StringRes.rightLeg: "오른쪽다리",
  StringRes.torso: "몸통",
  StringRes.todayFeedback: "오늘의 피드백",
  StringRes.emptyFeedback: "피드백이 없습니다.",
  StringRes.monthlySchedule: "월간 주요 일정",
  StringRes.todaySchedule: "오늘 일정",
  StringRes.contactDedicatedCoach: "전담코치에게 연락하기",
  StringRes.field: "필드",
  StringRes.period: "기간",
  StringRes.time: "시간",
  StringRes.place: "장소",
  StringRes.trainingContent: "훈련내용",
  StringRes.noSchedule: "일정이 없습니다.",
  StringRes.noAccounts: "기입된 계정이 없습니다.",
  StringRes.snsAccounts: "SNS로 가입한 계정입니다.",
  StringRes.resultOfSignedInId: "로 가입한 아이디 결과입니다.",
  StringRes.kakaoUser: "카카오회원",
  StringRes.naverUser: "네이버회원",
  StringRes.appleUser: "애플회원",
  StringRes.changeCompleteAndLogin: "변경완료 후 로그인",
  StringRes.identity: "아이디",
  StringRes.camera: "카메라",
  StringRes.album: "앨범",
};
