part of 'translations.dart';

class StringRes {
  static const _uuid = Uuid();

  /// DateTime 영역
  static final hourParams = _generateId();
  static final minParams = _generateId();

  /// 운동강도 레벨.
  static final intensityLevelVeryEasy = _generateId();
  static final intensityLevelVeryEasyDescription = _generateId();
  static final intensityLevelEasy = _generateId();
  static final intensityLevelEasyDescription = _generateId();
  static final intensityLevelNormal = _generateId();
  static final intensityLevelNormalDescription = _generateId();
  static final intensityLevelHard = _generateId();
  static final intensityLevelHardDescription = _generateId();
  static final intensityLevelVeryHard = _generateId();
  static final intensityLevelVeryHardDescription = _generateId();
  static final intensityLevelOver = _generateId();
  static final intensityLevelOverDescription = _generateId();

  /// 부상 타입.
  static final injuryTypeContact = _generateId();
  static final injuryTypeNonContact = _generateId();
  static final injuryTypeDisease = _generateId();
  static final injuryTypeContactSimple = _generateId();
  static final injuryTypeNonContactSimple = _generateId();
  static final injuryTypeDiseaseSimple = _generateId();

  /// 요일.
  static final weekDaySun = _generateId();
  static final weekDayMon = _generateId();
  static final weekDayTue = _generateId();
  static final weekDayWed = _generateId();
  static final weekDayThu = _generateId();
  static final weekDayFri = _generateId();
  static final weekDaySat = _generateId();

  /// 부상 레벨
  static final injuryLevelVeryHighPain = _generateId();
  static final injuryLevelHighPain = _generateId();
  static final injuryLevelInjured = _generateId();
  static final injuryLevelMildDiscomfort = _generateId();
  static final injuryLevelModeratePain = _generateId();
  static final injuryLevelNoPain = _generateId();
  static final injuryLevelVeryHighPainDescription = _generateId();
  static final injuryLevelHighPainDescription = _generateId();
  static final injuryLevelInjuredDescription = _generateId();
  static final injuryLevelMildDiscomfortDescription = _generateId();
  static final injuryLevelModeratePainDescription = _generateId();
  static final injuryLevelNoPainDescription = _generateId();

  /// 부상위험도 문구.
  static final injuryRiskVeryGood = _generateId();
  static final injuryRiskGood = _generateId();
  static final injuryRiskDangerous = _generateId();
  static final injuryRiskVeryDangerous = _generateId();

  /// 통증 양상.
  static final tingling = _generateId();
  static final pressure = _generateId();
  static final weakness = _generateId();
  static final numbness = _generateId();
  static final tightness = _generateId();
  static final postureSensitive = _generateId();
  static final aching = _generateId();
  static final stiff = _generateId();
  static final soreness = _generateId();
  static final sharpPain = _generateId();
  static final radiatingPain = _generateId();

  // 이력 공통 필터
  static final historyFilterAll = _generateId();
  static final historyFilterWeek = _generateId();
  static final historyFilterMonth = _generateId();
  static final historyFilterDesc = _generateId();
  static final historyFilterAsc = _generateId();
  static final historyFilterProgressInjury = _generateId();
  static final historyFilterHealedInjury = _generateId();

  /// 근육명 - 앞 - 몸
  static final TRAPEZIUS = _generateId(); // 승모근
  static final PECTORALIS_MAJOR = _generateId(); // 대흉근
  static final EXTERNAL_OBLIQUE = _generateId(); // 외복사근
  static final RECTUS_ABDOMINIS = _generateId(); // 복직근

  /// 근육명 - 팔
  static final DELTOID = _generateId(); // 삼각근
  static final BICEPS = _generateId(); // 이두근
  static final BRACHIORADIALIS = _generateId(); // 완요골근
  static final BRACHIALIS = _generateId(); // 상완근
  static final PRONATOR_TERES = _generateId(); // 원회내근
  static final PALMARIS_LONGUS = _generateId(); // 장장근
  static final TRICEPS = _generateId(); // 삼두근
  static final TENSOR_FASCIAE_LATAE = _generateId(); // 대퇴근막장근
  static final SARTORIUS = _generateId(); // 봉공근
  static final VASTUS_LATERALIS = _generateId(); // 외측광근
  static final RECTUS_FEMORIS = _generateId(); // 대퇴직근
  static final IT_BAND = _generateId(); // 장경인대
  static final EXTENSOR_DIGITORUM_LONGUS = _generateId(); // 장지신근
  static final TIBIALIS_ANTERIOR = _generateId(); // 전경골근
  static final FIBULARIS_LONGUS = _generateId(); // 장비골근
  static final EXTENSOR_HALLUCIS_LONGUS = _generateId(); // 장모지신근
  static final ILIACUS = _generateId(); // 장골근
  static final PSOAS_MAJOR = _generateId(); // 대요근
  static final PECTINEUS = _generateId(); // 치골근
  static final ADDUCTOR_LONGUS = _generateId(); // 장내전근
  static final ADDUCTOR_MAGNUS = _generateId(); // 대내전근
  static final GRACILIS = _generateId(); // 박근
  static final VASTUS_MEDIALIS = _generateId(); // 내측광근
  static final VASTUS_INTERMEDIUS = _generateId(); // 중간광근
  static final GASTROCNEMIUS = _generateId(); // 비복근
  static final SOLEUS = _generateId(); // 가자미근
  static final GLUTE = _generateId(); // 둔근
  static final CORACOBRACHIALIS = _generateId(); // 오훼완근

  /// 생성자.
  const StringRes._();

  static String _generateId() => _uuid.v1();

  static final appName = _generateId();
  static final serverError = _generateId();
  static final bottomTabHistory = _generateId();
  static final bottomTabHome = _generateId();
  static final bottomTabFeedback = _generateId();
  static final notification = _generateId();
  static final message = _generateId();
  static final messageChannelDescription = _generateId();
  static final email = _generateId();
  static final emailHint = _generateId();
  static final emailError = _generateId();
  static final emailDuplicated = _generateId();
  static final password = _generateId();
  static final passwordHint = _generateId();
  static final passwordError = _generateId();
  static final passwordConfirm = _generateId();
  static final passwordNotMatched = _generateId();
  static final simpleSignUp = _generateId();
  static final findId = _generateId();
  static final findPw = _generateId();
  static final login = _generateId();
  static final logout = _generateId();
  static final startWithSns = _generateId();
  static final acceptTerms = _generateId();
  static final allAgree = _generateId();
  static final requiredTermService = _generateId();
  static final requiredTermPrivacy = _generateId();
  static final next = _generateId();
  static final prev = _generateId();
  static final signUp = _generateId();
  static final phoneNumber = _generateId();
  static final phoneNumberError = _generateId();
  static final phoneHint = _generateId();
  static final name = _generateId();
  static final nameError = _generateId();
  static final nameHint = _generateId();
  static final findIdResult = _generateId();
  static final changePassword = _generateId();
  static final category = _generateId();
  static final sports = _generateId();
  static final clickToSelect = _generateId();
  static final amateur = _generateId();
  static final elite = _generateId();
  static final selectCategory = _generateId();
  static final selectSports = _generateId();
  static final search = _generateId();
  static final select = _generateId();
  static final myInformation = _generateId();
  static final teamName = _generateId();
  static final selectTeam = _generateId();
  static final height = _generateId();
  static final weight = _generateId();
  static final cm = _generateId();
  static final kg = _generateId();
  static final birth = _generateId();
  static final birthHint = _generateId();
  static final gender = _generateId();
  static final male = _generateId();
  static final female = _generateId();
  static final eightDigits = _generateId();
  static final positionMultipleSelectionPossible = _generateId();
  static final mainFoot = _generateId();
  static final leftFoot = _generateId();
  static final rightFoot = _generateId();
  static final registration = _generateId();
  static final confirm = _generateId();
  static final searchTeams = _generateId();
  static final logo = _generateId();
  static final clubName = _generateId();
  static final dedicatedCoach = _generateId();
  static final sir = _generateId();
  static final myState = _generateId();
  static final noData = _generateId();
  static final dataNotAvailable = _generateId();
  static final hooperIndex = _generateId();
  static final homeHooperIndexAverage = _generateId();
  static final hooperIndexAverage = _generateId();
  static final urinalysis = _generateId();
  static final urinalysisAverage = _generateId();
  static final urinalysisTable = _generateId();
  static final injuryRisk = _generateId();
  static final workoutIntensity = _generateId();
  static final workoutIntensityKorEng = _generateId();
  static final noRecordAndRecordYourStatusToday = _generateId();
  static final emptyWeightParams = _generateId();
  static final emptyWeight = _generateId();
  static final emptyWeightWarning = _generateId();
  static final emptyWeightGood = _generateId();
  static final workoutIntensityStatistics = _generateId();
  static final physical = _generateId();
  static final pleaseSelectCategory = _generateId();
  static final monthly = _generateId();
  static final weekly = _generateId();
  static final sleep = _generateId();
  static final sleepNoSpace = _generateId();
  static final sleepKorEng = _generateId();
  static final sleepEng = _generateId();
  static final stress = _generateId();
  static final stressKorEng = _generateId();
  static final stressEng = _generateId();
  static final fatigue = _generateId();
  static final fatigueKorEng = _generateId();
  static final fatigueEng = _generateId();
  static final musclePain = _generateId();
  static final musclePainKorEng = _generateId();
  static final musclePainEng = _generateId();
  static final urineVeryGood = _generateId();
  static final urineGood = _generateId();
  static final urineAppropriate = _generateId();
  static final urineDemand = _generateId();
  static final urineRecommended = _generateId();
  static final urineNeed = _generateId();
  static final urineEmergency = _generateId();
  static final urineNone = _generateId();
  static final workoutTime = _generateId();
  static final todayTime = _generateId();
  static final trainingBalance = _generateId();
  static final trainingBalanceFormula = _generateId();
  static final thisWeek = _generateId();
  static final lastWeek = _generateId();
  static final lastFourWeek = _generateId();
  static final lastEightWeek = _generateId();
  static final unitPercent = _generateId();
  static final informationRegistrationGuide = _generateId();
  static final doInformationRegistration = _generateId();
  static final wellness = _generateId();
  static final wellnessKorEng = _generateId();
  static final wellnessDescription = _generateId();
  static final injuryManagement = _generateId();
  static final injuryCheck = _generateId();
  static final injuryHistory = _generateId();
  static final injuryHistoryDescription = _generateId();
  static final close = _generateId();
  static final open = _generateId();
  static final veryVeryGood = _generateId();
  static final veryVeryBad = _generateId();
  static final satisfactory = _generateId();
  static final insufficient = _generateId();
  static final urineTestWeightKg = _generateId();
  static final myAnswer = _generateId();
  static final bmi = _generateId();
  static final bmiPercent = _generateId();
  static final compellingRequest = _generateId();
  static final doSave = _generateId();
  static final save = _generateId();
  static final doUpdate = _generateId();
  static final performedWorkout = _generateId();
  static final sportsTraining = _generateId();
  static final physicalTraining = _generateId();
  static final description = _generateId();
  static final intensity = _generateId();
  static final add = _generateId();
  static final painCheckLocation = _generateId();
  static final injuryLocationSelection = _generateId();
  static final injuryCheckDiseaseHint = _generateId();
  static final front = _generateId();
  static final back = _generateId();
  static final upperBody = _generateId();
  static final lowerBody = _generateId();
  static final leftArm = _generateId();
  static final rightArm = _generateId();
  static final leftLeg = _generateId();
  static final rightLeg = _generateId();
  static final torso = _generateId();
  static final todayFeedback = _generateId();
  static final emptyFeedback = _generateId();
  static final monthlySchedule = _generateId();
  static final todaySchedule = _generateId();
  static final contactDedicatedCoach = _generateId();
  static final field = _generateId();
  static final period = _generateId();
  static final time = _generateId();
  static final place = _generateId();
  static final trainingContent = _generateId();
  static final noSchedule = _generateId();
  static final noAccounts = _generateId();
  static final snsAccounts = _generateId();
  static final resultOfSignedInId = _generateId();
  static final kakaoUser = _generateId();
  static final naverUser = _generateId();
  static final appleUser = _generateId();
  static final changeCompleteAndLogin = _generateId();
  static final identity = _generateId();
  static final camera = _generateId();
  static final album = _generateId();
  static final detailedMuscle = _generateId();
  static final painLevel = _generateId();
  static final painSymptoms = _generateId();
  static final painTiming = _generateId();
  static final intermittent = _generateId();
  static final regular = _generateId();
  static final restPeriod = _generateId();
  static final duringWorkout = _generateId();
  static final injuryCause = _generateId();
  static final injuryCauseHint = _generateId();
  static final noRegisteredTeam = _generateId();
  static final teamSelect = _generateId();
  static final complete = _generateId();
  static final pushSelect = _generateId();
  static final teamRequest = _generateId();
  static final appleNeedPass = _generateId();
  static final signOut = _generateId();
  static final doSignOut = _generateId();
  static final signOutDescription = _generateId();
  static final authCode = _generateId();
  static final authCodeHint = _generateId();
  static final managementRequired = _generateId();
  static final delete = _generateId();
  static final deleteDialog = _generateId();
  static final painPosition = _generateId();
  static final signUpComplete = _generateId();
  static final registrationCompletedAfterAdminApproval = _generateId();
  static final writeInBodyRecord = _generateId();
  static final moistureGood = _generateId();
  static final moistureLack = _generateId();
  static final trainingBalanceNone = _generateId();
  static final trainingBalanceLess = _generateId();
  static final trainingBalanceNormal = _generateId();
  static final trainingBalanceOver = _generateId();
  static final urineWeightLessMoistureGood = _generateId();
  static final urineWeightLessMoistureBad = _generateId();
  static final urineWeightGoodMoistureGood = _generateId();
  static final urineWeightGoodMoistureBad = _generateId();
  static final urineWeightOverMoistureGood = _generateId();
  static final urineWeightOverMoistureBad = _generateId();
  static final progress = _generateId();
  static final proceeding = _generateId();
  static final recovery = _generateId();
  static final recoveryCompleteQuestion = _generateId();
  static final yes = _generateId();
  static final no = _generateId();
  static final myHistory = _generateId();
  static final whatWellness = _generateId();
  static final wellnessGuide = _generateId();
  static final workoutTimeAverage = _generateId();
  static final workoutIntensityAverage = _generateId();
  static final step = _generateId();
  static final filter = _generateId();
  static final sortBy = _generateId();
  static final inquiryPeriod = _generateId();
  static final todayTraining = _generateId();
  static final noRegisteredTrainingToday = _generateId();
  static final beCarefulWorkingOutToday = _generateId();
  static final moreShow = _generateId();
  static final urineState = _generateId();
  static final injuryCurrentSituation = _generateId();
  static final risk7LessThan = _generateId();
  static final risk7To14 = _generateId();
  static final risk14To21 = _generateId();
  static final risk21More = _generateId();
  static final drinkingGood = _generateId();
  static final drinkingWarning = _generateId();
  static final drinkingDanger = _generateId();
  static final eatingGood = _generateId();
  static final eatingNeed = _generateId();
  static final eatingOver = _generateId();
  static final enterIntensityBeforeForget = _generateId();
  static final cancel = _generateId();
  static final waterIntakeStatus = _generateId();
  static final verify = _generateId();
  static final reVerify = _generateId();
  static final selectPosition = _generateId();
  static final duration = _generateId();
  static final urineColor = _generateId();
  static final bodyFat = _generateId();
  static final drinkGood = _generateId();
  static final drinkShortage = _generateId();
  static final agree = _generateId();
}
