///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String backgroundBottom = 'assets/images/background_bottom.svg';
  static const String backgroundTop = 'assets/images/background_top.svg';
  static const String camera = 'assets/images/camera.svg';
  static const String check = 'assets/images/check.svg';
  static const String checkBlue = 'assets/images/check_blue.svg';
  static const String checkOff = 'assets/images/check_off.svg';
  static const String checkOn = 'assets/images/check_on.svg';
  static const String checkRed = 'assets/images/check_red.svg';
  static const String chevronRight = 'assets/images/chevron-right.svg';
  static const String codeBrowser = 'assets/images/code_browser.svg';
  static const String edit03 = 'assets/images/edit03.svg';
  static const String foot = 'assets/images/foot.svg';
  static const String hand = 'assets/images/hand.svg';
  static const String hand2 = 'assets/images/hand2.png';
  static const String icChevronright = 'assets/images/ic_chevronright.svg';
  static const String imgApple = 'assets/images/img_apple.png';
  static const String imgEmail = 'assets/images/img_email.png';
  static const String imgKakao = 'assets/images/img_kakao.png';
  static const String imgNaver = 'assets/images/img_naver.png';
  static const String logo = 'assets/images/logo.svg';
  static const String navigationData = 'assets/navigation_data.svg';
  static const String navigationDataSelect = 'assets/navigation_data_select.svg';
  static const String navigationFeedback = 'assets/navigation_feedback.svg';
  static const String navigationFeedbackSelect = 'assets/navigation_feedback_select.svg';
  static const String navigationHome = 'assets/navigation_home.svg';
  static const String navigationHomeSelect = 'assets/navigation_home_select.svg';
  static const String noneWalkMan = 'assets/images/none_walk_man.svg';
  static const String phonePrimary = 'assets/images/phone_primary.svg';
  static const String retiredMan = 'assets/images/retired_man.svg';
  static const String runningMan = 'assets/images/running_man.svg';
  static const String searchRefraction = 'assets/images/search-refraction.svg';
  static const String splash = 'assets/images/splash.png';
  static const String starYellow = 'assets/images/star_yellow.svg';
  static const String triangle = 'assets/images/triangle.png';
  static const String userDefault = 'assets/images/user_default.svg';
  static const String userDefaultBasic = 'assets/images/user_default_basic.svg';
  static const String walkMan = 'assets/images/walk_man.svg';
  static const String xClose = 'assets/images/x-close.svg';

}
