///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesImgApple = 'assets/images/img_apple.svg';
  static const String imagesImgKakao = 'assets/images/img_kakao.svg';
  static const String imagesImgNaver = 'assets/images/img_naver.svg';

}
