default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :match_test do
      sync_code_signing(
        type: "appstore",
        app_identifier: "com.conner.physicalNote",
            force_for_new_devices: true,
        readonly: false
      )

  end

  lane :release do

#     match(type: "appstore")

     sync_code_signing(
       type: "appstore",
       app_identifier: "com.conner.physicalNote",
           force_for_new_devices: true,
       readonly: false
     )

    sh 'flutter build ios --release --flavor prod -t lib/app/config/env/prod.dart --no-tree-shake-icons'

    build_app(workspace: "Runner.xcworkspace", scheme: "prod")

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,  # 심사 자동 제출
      automatic_release: false,  # 승인 시 자동 출시
    )
  end
end
