default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do

    match(type: "appstore")

    sh 'flutter build ios --release --flavor prod -t lib/app/config/env/prod.dart --no-tree-shake-icons'

    build_app(workspace: "Runner.xcworkspace", scheme: "prod")

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,  # 심사 자동 제출
      automatic_release: false,  # 승인 시 자동 출시
    )
  end
end
