default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :sync_signing do
      #  2중 인증 대신 접근 권한 설정
      api_key = app_store_connect_api_key(
        key_id: ENV["APPSTORE_KEY_ID"],
        issuer_id: ENV["APPSTORE_ISSUER_ID"],
        key_content: ENV["APPSTORE_KEY_CONTENT"],  #
        is_key_content_base64: true,
        duration: 1200,
        in_house: false
      )
      sync_code_signing(
        type: "appstore",
        app_identifier: "com.conner.physicalNote",
            force_for_new_devices: true,
        readonly: false,
        api_key: api_key
      )

  end

  lane :release do

#     match(type: "appstore")

     #  2중 인증 대신 접근 권한 설정
     api_key = app_store_connect_api_key(
       key_id: ENV["APPSTORE_KEY_ID"],
       issuer_id: ENV["APPSTORE_ISSUER_ID"],
       key_content: ENV["APPSTORE_KEY_CONTENT"],  #
       is_key_content_base64: true,
       duration: 1200,
       in_house: false
     )

     sync_code_signing(
       type: "appstore",
       app_identifier: "com.conner.physicalNote",
           force_for_new_devices: true,
       readonly: false,
       api_key: api_key
     )

    build_app(workspace: "Runner.xcworkspace", scheme: "prod")

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,  # 심사 자동 제출
      automatic_release: false,  # 승인 시 자동 출시
    )
  end
end
