name: Update Version

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 버전 업데이트를 위해 write 권한 필요
          token: ${{ secrets.GITHUB_TOKEN }}

      # pubspec.yaml 버전 업데이트
      - name: Update pubspec version
        uses: stikkyapp/update-pubspec-version@v2
        with:
          strategy: 'patch'  # major, minor, patch 중 선택
          bump-build: true   # build 번호도 증가
          path: './pubspec.yaml'

      # 변경사항 커밋 & 푸시
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add pubspec.yaml
          git commit -m "chore: Bump version in pubspec.yaml"
          git push